SIGRES/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from sala_reuniones.views import RegisterView, HomeView
app_name = "sala_reuniones"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registrarse/$', RegisterView.as_view(), name='registrarse'),
    url(r'login/$', LoginView.as_view(template_name='sala_reuniones/entrar.html'), name='entrar'),
    url(r'^salir/$', LogoutView.as_view(), name='salir'),
    url(r'^sala_reuniones/', include(('sala_reuniones.urls'), namespace='sala_reuniones')),
    url(r'^$', HomeView.as_view(), name='home'),
]

sala_reuniones/urls.py
from django.conf.urls import url

from .views import (AdicionarReservaView,
                    ListarReservasViews,
                    ReservasFullcalendario,
                    EditarReservaView,
                    EliminarReservasView)

app_name = "sala_reuniones"
urlpatterns = [

    url(r'^adicionar/reserva/(?P<pk>\d+)/$', AdicionarReservaView.as_view(), name='adicionar_reserva'),
    url(r'^listar/reservas/$', ListarReservasViews.as_view(), name='listar_reservas'),
    url(r'^listar/reservas/calendario/$', ReservasFullcalendario.as_view(), name='calendario_reservas'),
    url(r'^editar/reserva/(?P<pk>\d+)/$', EditarReservaView.as_view(), name='editar_reserva'),
    url(r'^eliminar/reserva/(?P<pk>\d+)/$', EliminarReservasView.as_view(), name='eliminar_reserva')

]

sala_reuniones/models.py
# -*- encoding:utf-8 -*-
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


# Create your models here.


class Insumo(models.Model):
    nombre = models.CharField(max_length=30)

    class Meta:
        ordering = ['nombre']

    def __unicode__(self):
        return unicode(self.nombre)

    def __str__(self):
        return self.nombre


class HorarioDisponibilidad(models.Model):
    hora_inicio = models.TimeField(verbose_name='Hora de inicio')
    hora_fin = models.TimeField(verbose_name='Hora de terminar')

    class Meta:
        ordering = ['hora_inicio']
        verbose_name_plural = 'Horario disponibilidades'

    def __unicode__(self):
        return unicode(str(self.hora_inicio) + ' - ' + str(self.hora_fin))

    def __str__(self):
        return str(self.hora_inicio) + ' - ' + str(self.hora_fin)


class SalaReuniones(models.Model):
    nombre = models.CharField(max_length=50)
    ubicacion = models.CharField(max_length=100, verbose_name=u'Ubicación')
    capacidad = models.IntegerField()
    horario_disponibilidad = models.ManyToManyField(HorarioDisponibilidad)
    insumos = models.ManyToManyField(Insumo, default=['Proyector', u'Pizarrón'], blank=True)

    class Meta:
        ordering = ['nombre']
        verbose_name_plural = 'Sala de reuniones'

    def __unicode__(self):
        return unicode(self.nombre)

    def __str__(self):
        return self.nombre


class Reserva(models.Model):
    NO_DISPONIBLE = 'nd'
    DISPONIBLE = 'd'
    RESERVADA = 'r'
    CONFIRMADA = 'c'

    ESTADO_CHOICES = (
        (NO_DISPONIBLE, 'No disponible'),
        (DISPONIBLE, 'Disponible'),
        (RESERVADA, 'Reservada'),
        (CONFIRMADA, 'Confirmada')
    )

    fecha = models.DateField()
    hora_inicio = models.TimeField(verbose_name='Hora inicial')
    hora_final = models.TimeField(verbose_name='Hora final')
    capacidad = models.IntegerField(verbose_name='Capacidad de personas', default=10)
    sala_reuniones = models.ForeignKey(SalaReuniones, on_delete=models.DO_NOTHING,default=1)
    confirmada = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default=DISPONIBLE)

    class Meta:
        ordering = ['fecha', 'sala_reuniones']

    def __str__(self):
        return (str(self.fecha) + ' ' + self.sala_reuniones.nombre + ' ' + str(self.hora_inicio.strftime('%H:%M')) + ' ' + str(self.hora_final.strftime('%H:%M')))
        # .strftime('%d-%b-%Y')

sala_reuniones/forms.py
# -*- encoding:utf-8 -*-
# -*- coding:utf-8 -*-

from datetime import datetime, timedelta

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q


from .models import Reserva, SalaReuniones
from .widgets import DatePicker, TimePicker


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ReservaForm(forms.ModelForm):
    use_required_attribute = False

    class Meta:
        model = Reserva
        fields = ['fecha', 'hora_inicio', 'hora_final', 'capacidad', 'sala_reuniones', 'user']
        widgets = {
            'fecha': DatePicker,
            'hora_inicio': TimePicker,
            'hora_final': TimePicker
        }

    def __init__(self, *args, **kwargs):

        if 'pk' in kwargs:
            pk_sala = kwargs.pop('pk')

        super(ReservaForm, self).__init__(*args, **kwargs)
        if not self.instance.id:
            sala_reunion = SalaReuniones.objects.get(pk=pk_sala)
            self.fields['user'].required = False
            self.fields['sala_reuniones'].initial = sala_reunion

    def clean_fecha(self):
        fecha = self.cleaned_data['fecha']

        if fecha < datetime.now().date():
            raise forms.ValidationError('Este campo no admite fechas en el pasado.', code='invalid')

        return fecha

    def clean_hora_final(self):
        hora_final = self.cleaned_data['hora_final']

        try:
            hora_inicio = self.cleaned_data['hora_inicio']
        except KeyError:
            hora_inicio = ''

        if hora_inicio:
            if hora_final < hora_inicio:
                raise forms.ValidationError('La hora final no puede ser menor que la hora inicial.')

        return hora_final

    def clean_sala_reuniones(self):
        sala_reunion = self.cleaned_data['sala_reuniones']

        try:
            hora_inicio = self.cleaned_data['hora_inicio']
            hora_final = self.cleaned_data['hora_final']
        except KeyError:
            return sala_reunion

        
        for horario in sala_reunion.horario_disponibilidad.all():
            if hora_inicio < horario.hora_inicio or hora_inicio > horario.hora_fin:
                self.add_error('hora_inicio', 'No hay disponibilidad a esta hora.')
            if hora_final < horario.hora_inicio or hora_final > horario.hora_fin:
                self.add_error('hora_final', 'No hay disponibilidad en este horario.')
                
                

        

        return sala_reunion

    def clean(self):
        

        try:
            fecha = self.cleaned_data['fecha']
            hora_inicio = self.cleaned_data['hora_inicio']
            hora_final = self.cleaned_data['hora_final']
            fechaForm = fecha
            H_i=hora_inicio.hour
            # H_i.isoformat(timespec='auto') 

        except KeyError:
            return self.cleaned_data

        cantReservas = Reserva.objects.filter(Q(fecha=fecha),Q(Q(hora_inicio__gt=hora_inicio), Q(hora_inicio__lt=hora_final))| Q(Q(hora_final__gt=hora_inicio), Q(hora_final__lt=hora_final))).count()

        if cantReservas >0:
            print('      **************       ')
            print(cantReservas)
            print(fechaForm)
            raise forms.ValidationError('Ya existe una reserva en esa fecha y rango de horarios.')
            

        return self.cleaned_data

sala_reuniones/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from distutils import errors
from distutils.log import ERROR

from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, View, TemplateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User

from .models import SalaReuniones, Reserva
from .forms import UserRegisterForm, ReservaForm

from braces.views import LoginRequiredMixin, FormValidMessageMixin
from datetime import datetime, timedelta


# Create your views here.


class HomeView(ListView):
    model = SalaReuniones
    template_name = 'sala_reuniones/home.html'
    context_object_name = 'salas_reuniones'

    def get_context_data(self, *args, **kwargs):
        context_data = super(HomeView, self).get_context_data(*args, **kwargs)
        reserva=Reserva.objects.filter(fecha=datetime.now().date()).order_by('fecha')        
        context_data['reservas'] = reserva
        print(reserva)
        
        return context_data


class RegisterView(View):
    template_name = 'sala_reuniones/register.html'

    def get(self, request, *args, **kwargs):
        form = UserRegisterForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            messages.success(request, 'Cuenta creada para %s !!!' % username)
            form.save()
            return redirect('home')
        return render(request, self.template_name, {'form': form})


class AdicionarReservaView(LoginRequiredMixin, CreateView):
    model = Reserva
    form_class = ReservaForm
    success_url = reverse_lazy('sala_reuniones:calendario_reservas')

    def form_valid(self, form):
        formulario = form.save(commit=False)
        formulario.user = self.request.user

        # if formulario.confirmada:
        #     formulario.estado = Reserva.CONFIRMADA
        # else:
        #     formulario.estado = Reserva.RESERVADA
        formulario.estado = Reserva.CONFIRMADA

        formulario.save()

        return super(AdicionarReservaView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context_data = super(AdicionarReservaView, self).get_context_data(*args, **kwargs)
        sala_reunion = SalaReuniones.objects.get(pk=self.kwargs['pk'])
        hoy = datetime.date(datetime.now())
        Dia_reserva= hoy


        context_data['sala_reunion'] = sala_reunion
        context_data['horarios'] = sala_reunion.horario_disponibilidad.all()
        context_data['aux'] = hoy
        context_data['aux2'] = Dia_reserva
        # error = ReservaForm.hora_final.error_messages
        # print(error)
        

        return context_data

    def get_form_kwargs(self):
        kwargs = super(AdicionarReservaView, self).get_form_kwargs()
        kwargs['pk'] = self.kwargs['pk']
        return kwargs

    


class ListarReservasViews(ListView):
    model = Reserva
    context_object_name = 'reservas'


class ReservasFullcalendario(TemplateView):
    template_name = 'sala_reuniones/fullcalendar.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super(ReservasFullcalendario, self).get_context_data(*args, **kwargs)
        context_data['reservas'] = Reserva.objects.all()
        # print(context_data['reservas'])
        return context_data


class EditarReservaView(LoginRequiredMixin, FormValidMessageMixin, UpdateView):
    model = Reserva
    form_class = ReservaForm
    form_valid_message = 'Se ha editado la reserva satisfactoriamente.'
    success_url = reverse_lazy('sala_reuniones:calendario_reservas')

    def get_context_data(self, *args, **kwargs):
        reserva = Reserva.objects.get(pk=self.kwargs['pk'])
        hoy = datetime.date(datetime.now())
        Dia_reserva = reserva.fecha


        context_data = super(EditarReservaView, self).get_context_data(*args, **kwargs)
        context_data['sala_reunion'] = reserva.sala_reuniones
        context_data['horarios'] = reserva.sala_reuniones.horario_disponibilidad.all()
        context_data['editar'] = True
        context_data['pk'] = self.object.pk
        context_data['aux'] = hoy
        context_data['aux2'] = Dia_reserva

        

        return context_data

    # @property
    # def is_past_due(self):
    #     aux = datetime.date.today()
    #     return aux


class EliminarReservasView(LoginRequiredMixin, DeleteView):
    model = Reserva
    success_url = reverse_lazy('sala_reuniones:listar_reservas')

sala_reuniones/templates/sala_reuniones/barra_navegacion.html
<nav class="navbar navbar-default navbar-fixed-top ">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="container">
                <ul class="nav navbar-nav navbar-center">
                    {% if  user.is_authenticated %}
                        <li><a href="" style="color: #000000;">Logout</a></li>
                    {% else %}
                        <li><a href="" style="color: #000000">Login</a></li>
                        <li><a href="" style="color: #000000;">Registrarse</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</nav>

sala_reuniones/templates/sala_reuniones/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% load static %}


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/fullcalendar/fullcalendar.min.css' %}" type="text/css">
    
    {% block css %} {% endblock css %}

    <title>Reserva de salas de reuniones</title>
    
</head>
<body>

{#    {% include 'sala_reuniones/barra_navegacion.html' %}#}

    
        <h1>Reserva de salas de reuniones</h1>
        
            <ul class="nav nav-tabs" id="custom-tabs-one-tab" role="tablist">
                <li class="nav-item">
                    <a href="{% url 'home' %}">Inicio</a> 
                </li>
                
                
                
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'sala_reuniones:calendario_reservas' %}">Calendario</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'salir' %}">Salir</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'entrar' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'registrarse' %}">Registrarse</a>
                    </li>
                {% endif %} 
            </ul>
        
        
        <div class="pull-right">
            {% if not user.is_anonymous %}
                Bienvenido <strong><em>{{ user.username }} 
                {% if user.is_superuser %}
                    <a href="/admin">(admin)</a>
                {% else%}
                    (user)
                {% endif %}
                        </em></strong>
            {% endif %}
        </div>
        <hr>
        {% block content_out %}
            <div class="row">
                <div class="col-md-offset-3 col-md-4">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                    {% block content %} {% endblock %}
                </div>
                <div class="col-md-offset-1 col-md-3">
                    {% block content_extra %} {% endblock content_extra %}                
                </div>
            </div>    
        {% endblock content_out %}
        

    

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/fullcalendar/moment.min.js' %}"></script>
    <script src="{% static 'js/fullcalendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'js/fullcalendar/es.js' %}"></script>
    

    {% block js_extra %}{% endblock %}

</body>
</html>

sala_reuniones/templates/sala_reuniones/entrar.html
{%  extends 'sala_reuniones/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading"><strong>Entrar</strong></div>
		<div class="panel-body">
			<form action="" method="POST">{% csrf_token %}
				<div class="form-group">
					{{ form|crispy }}
				</div>
				<hr>
				<button class="btn btn-default" type="Submit">Entrar</button>
			</form>
		</div>
	</div>
</div>	
{% endblock content %}

sala_reuniones/templates/sala_reuniones/fullcalendar.html
{% extends "sala_reuniones/base.html" %}

{% block content_out %}
<section class="content">
	<div class="container-fluid">
	  <!-- SELECT2 EXAMPLE -->
	  <div class="card card-default">
		<!-- /.card-header -->
		<div class="card-header">
			<div class="pull-left">
				
				{% if user.is_authenticated %}
				<a class="btn btn-warning" href="http://192.168.0.13:8080/sala_reuniones/adicionar/reserva/1/">Reservar</a>
				
				{% endif %}
			</div>
		</div>
		<div class="card-body">
		  <div class="row">
			<div class="col-md-6">
				<div id="calendar"></div>
			</div>
		  </div>
		</div>
	</div>
</section>
{% endblock content_out %}

{% block js_extra %}
	<script>

		
		$(document).ready(function(){
			
			
			$('#calendar').fullCalendar({
				headerToolbar: {
					left  : 'prev,next today',
					center: 'title',
					right : 'dayGridMonth,timeGridWeek,timeGridDay'
				},
				editable: true,
				events: [
				{% for reserva in reservas %}
					
					{	
						// title: "{% if reserva.estado == 'r'  %}\
						// Reservada	\
						// {% elif reserva.estado == 'c'%}\
						// Confirmada\
						// {% endif %} {{ reserva.hora_final|safe }}",
						title: "{{ reserva.user.username|safe }} {{ reserva.hora_final|safe }}",
						start: "{{ reserva.fecha|safe }} {{ reserva.hora_inicio|safe }}",
						end: "{{ reserva.fecha|safe }} {{ reserva.hora_final|safe }}",
						id: "{{ reserva.pk }}",
						backgroundColor: "{% if reserva.pk|divisibleby:2 == True  %}\
						#666\
						{% else %}\
						#28a745\
						{% endif %}",
						borderColor : "{% if reserva.pk|divisibleby:2 == True  %}\
						#666\
						{% else %}\
						#28a745\
						{% endif %}",

						
						
					},
				{% endfor %}
				],
			
					eventClick: function(event, element){
						var id = event.id;

						window.location = "http://192.168.0.13:8080/sala_reuniones/editar/reserva"+"/"+ id + "/" ;
						
					}
				

			});
		});

	</script>
{% endblock js_extra %}

sala_reuniones/templates/sala_reuniones/home.html
{% extends 'sala_reuniones/base.html' %}


{% block content %}

        <!-- <div class="col-lg-12"> -->

            {% for sala in salas_reuniones %}
                <div class="panel panel-primary">
                    <div class="panel-heading">{{sala.nombre}}</div>
                    <div class="panel-body">
                        <p>Ubicaci&oacute;n: {{sala.ubicacion}}</p>
                        <!-- <p>Capacidad: {{sala.capacidad}}</p> -->
                        
                        <p>Horario de disponibilidad: <br>
                            <div>
                                {% for horario in sala.horario_disponibilidad.all %}
                                    <span class="label label-primary">{{ horario }}</span> <br>
                                {% endfor %}
                            </div>
                        </p>
                    </div>
                    
                    <div class="panel-footer">
                        <a class="btn btn-success" href="{% url 'sala_reuniones:adicionar_reserva' pk=sala.pk %}">Reservar</a>
                    </div>
                

                </div>
            {% endfor %}
{% endblock %}

{% block content_extra %}

    
        
        <div class="col-md-8">
            <h2> Para hoy </h2>
            <div class="panel-group">       
                {% if reservas%}
                
                    {% for reserva in reservas %}
                    
                        <div class="panel panel-default">
                            <div class="panel-body">
                                Horario: <span class="label label-default"> {{ reserva.hora_inicio }} - {{ reserva.hora_final }} </span>  
                                Usuario: <span class="label label-primary">{{ reserva.user.username }}</span></div>
                        </div>

                    {% endfor %}
                    {% else %}
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <strong><em>No hay reservas</em></strong>
                            </div>
                        </div>
                {% endif %}
            </div>
        </div>
    
{% endblock content_extra %}


{% block js_extra %}
    <script type="text/javascript">
        $(document).ready(function(){

            $('[data-toggle="tooltip"]').tooltip({placement: 'right'});

        });
    </script>

{% endblock %}

sala_reuniones/templates/sala_reuniones/register.html
{% extends "sala_reuniones/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading"><strong>Registrarse</strong></div>
			<div class="panel-body">
				<form action="" method="POST">{% csrf_token %}
					<div class="form-group">
						{{ form|crispy }}
					</div>
					<hr>
					<div class="form-group">
						<button class="btn btn-default" type="Submit">Registrarse</button>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

sala_reuniones/templates/sala_reuniones/reserva_confirm_delete.html
{% extends "sala_reuniones/base.html" %}

{% block content %}
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">Eliminar</div>
			<div class="panel-body">
				<form action="" method="POST">{% csrf_token %}
					<p>Seguro q desea eliminar la reserva del sal&oacute;n 
						<span class="label label-warning">
							<em>{{ object.sala_reuniones.nombre}}</em>
						</span> 
						para el 
						<span class="label label-default">{{object.fecha}}</span>
						de <span class="label label-default">{{object.hora_inicio}} - {{object.hora_final}}</span>?
					</p>
					<br>
					<br>
					<br>
					<div class="form-group">
						<button class="btn btn-block btn-danger" type="submit">Eliminar</button>
					</div>
				</form>
				
			</div>
		</div>

	</div>
{% endblock content %}

sala_reuniones/templates/sala_reuniones/reserva_form.html
{% extends "sala_reuniones/base.html" %}
{% load crispy_forms_tags %}

{% block css %}
	{{ form.media.css }}
{% endblock css %}


{% block content %}
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading"><strong>Agregar reserva</strong></div>	
			<div class="panel-body">
				<form action="" method="POST">{% csrf_token %}
					<div class="form-group">
						{{ form|crispy }}
					</div>
					{% if user.id == reserva.user_id or reserva.user_id == nulla %}
						{% if aux2 >= aux  %}
							<div class="form-group">
								<button class="btn btn-default" type="submit">
									{% if editar %}
										Editar
									{% else %}
										Reservar
									{% endif %}
								</button>
								{% if editar %}
									<a href="{% url 'sala_reuniones:eliminar_reserva' pk=pk  %}" class="btn btn-danger">Eliminar</a>
								{% endif %}
								

							</div>
						{% endif %}	
					{% endif %}
					<a href="http://192.168.0.13:8080/sala_reuniones/listar/reservas/calendario/" class="btn btn-success">Volver</a>
				</form>
			</div>
		</div>
	</div>
	
		{% if aux2 < aux  %}
					<div class="panel-footer">
						<div class="alert alert-danger">
							<strong>¡Atención!</strong>
							Esta reserva ya pasó.
						</div>
					</div>
		{% endif %}	
		<!-- {% if form.errors  %}
					<div class="panel-footer">
						<div class="alert alert-danger">
							<strong>¡Atención!</strong>
							{{ form.errors }}
						</div>
					</div>
		{% endif %}	 -->

	
{% endblock content %}

{% block content_extra %}
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">{{ sala_reunion }}</div>
			<div class="panel-body">
				<strong>Horarios:</strong><br>
				{% for horario in horarios %}
					<span class="label label-primary">{{ horario }}</span>
				{% endfor %}

			</div>
		</div>
	</div>
{% endblock content_extra %}

{% block js_extra %}

	{{ form.media.js }}
	<script>
		$(document).ready(function(){
			$.fn.datepicker.defaults.language = 'es';

			$('#id_fecha').datepicker({

				autoclose: true,
				todayHighlight: true,
				format: 'dd/mm/yy'
			});

			$('#div_id_user').hide();

			$('#div_id_hora_inicio').clockpicker({
				donetext: 'Done',
				autoclose: true
			});
			
			$('#div_id_hora_final').clockpicker({
				donetext: 'Done',
				autoclose: true
			});

		});
	</script>
{% endblock js_extra %}

sala_reuniones/templates/sala_reuniones/reserva_list.html
{% extends "sala_reuniones/base.html" %}

{% block content %}
    
    {% if reservas%}
    	{% for reserva in reservas %}
    		<div class="panel panel-default">
                <div class="panel-heading">
                     <p>
                        
                        Fecha: {{ reserva.fecha }}
                    </p>
                </div>
                <div class="panel-body">
                    <!-- <p>Fecha: {{ reserva.fecha }}</p> -->
                    <p>ID: 
                        <span class="label label-primary">
                            {{ reserva.pk }}
                        </span>
                    </p>
                    <p>Horario:
                        <span class="label label-default">
                            {{ reserva.hora_inicio }} - {{ reserva.hora_final }}
                        </span>
                    </p>
                    <p>Ubicaci&oacute;n: {{reserva.sala_reuniones.ubicacion}}</p>
                    <p>Capacidad: {{reserva.sala_reuniones.capacidad}}</p>
                    <p>Insumos: {{ reserva.sala_reuniones.insumos.all|join:", " }}</p>
                    <p>Usuario: 
                        <span class="label label-primary">
                            {{ reserva.user.username }}
                        </span>
                    </p>
                   
                    {% if reserva.estado == 'd' %}
                        <p>Estado: <span class="label label-success">Disponible</span> </p>
                    {% elif reserva.estado == 'c' and user.username != reserva.user.username %}
                        <p>Estado: <span class="label label-danger" data-toggle="tooltip"  data-original-tittle="No se puede editar">No disponible</span></p>
                    {% elif reserva.estado == 'r'  %}
                        <p>Estado: <span class="label label-warning">Reservada</span> </p>
                    {% elif reserva.estado == 'c' and user.username == reserva.user.username %}
                        <p>Estado: <span class="label label-info">Confirmada</span></p>
                    {% endif %}
                </div>
                {% if reserva.estado != 'c'%}
                    <div class="panel-footer">
                        <a class="btn btn-default" href="{% url 'sala_reuniones:editar_reserva' pk=reserva.pk %}">Editar</a>
                        {% if user.is_superuser %}
                            <a href="{% url 'sala_reuniones:eliminar_reserva' pk=reserva.pk %}" class="btn btn-danger">
                                Eliminar
                            </a>
                            
                        {% endif %}
                    </div>
                {% endif %}
            </div>
    	{% endfor %}
        {% else %}
            <h3><strong><em>No se han realizado reservas hasta el momento</em></strong></h3>
    {% endif %}
{% endblock content %}